### ISSUE TITLE
[Feature request] ProLayout

### ISSUE THREAD

**Issue by robin-dongbin** [Zheng-Changfu/pro-components-naive-ui#41]
希望能提供布局组件，类似 Ant design pro 的 layout

**Comment by Zheng-Changfu** [comment]
还在开发中，目前在做table组件，可以共建

---- Replied Message ----
| From | Robin ***@***.***> |
| Date | 10/16/2024 20:33 |
| To | Zheng-Changfu/pro-components-naive-ui ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [Zheng-Changfu/pro-components-naive-ui] [Feature request] ProLayout (Issue #41) |

希望能提供布局组件，类似 Ant design pro 的 layout

**Comment by Zheng-Changfu** [comment]
可以进群交流

---- Replied Message ----
| From | Robin ***@***.***> |
| Date | 10/16/2024 20:33 |
| To | Zheng-Changfu/pro-components-naive-ui ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [Zheng-Changfu/pro-components-naive-ui] [Feature request] ProLayout (Issue #41) |

希望能提供布局组件，类似 Ant design pro 的 layout

**Comment by Zheng-Changfu** [comment]
![交流群](https://github.com/user-attachments/assets/2a58c9bc-34d7-4e95-afd9-8c7607c2387e)
